OkunmusPirinc.Web/Controllers/CategoriesController.cs
using OkunmusPirinc.DatabaseAccess;
using OkunmusPirinc.Entities.Concretes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OkunmusPirinc.Web.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        public ActionResult AnaKategoriler()
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.ProductCategoryRepo.GetAll().ToList().FindAll(x=>x.MainCategoryID == null));
        }
        public ActionResult AltKategoriler(int id)
        {
            List<ProductCategory> categories = new List<ProductCategory>();
            using (UnitOfWork uow = new UnitOfWork())
                categories = uow.ProductCategoryRepo.GetAll().ToList().FindAll(x => x.MainCategoryID == id);
            if (categories.Count == 0)
                return Redirect("/Product/Urunler/"+id);
            return View(categories);
        }
    }
}

OkunmusPirinc.Web/Controllers/HomeController.cs
using OkunmusPirinc.DatabaseAccess;
using OkunmusPirinc.Entities.Concretes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OkunmusPirinc.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Anasayfa()
        {
            List<ProductCategory> categories = new List<ProductCategory>();
            List<Product> products = new List<Product>();
            using (UnitOfWork uow = new UnitOfWork())
            {
                categories = uow.ProductCategoryRepo.GetAll().ToList();
                products = uow.ProductRepo.ProductsWithCategories().ToList();
            }
            ListItem lists = new ListItem(products, categories);
                return View(lists);
        }
    }
}

OkunmusPirinc.Web/Controllers/ProductController.cs
using OkunmusPirinc.DatabaseAccess;
using OkunmusPirinc.Entities.Concretes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OkunmusPirinc.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult TumUrunler(int page = 1)
        {
            List<ProductCategory> categories = new List<ProductCategory>();
            List<Product> products = new List<Product>();
            using (UnitOfWork uow = new UnitOfWork())
            {
                categories = uow.ProductCategoryRepo.GetAll().ToList();
                products = uow.ProductRepo.ProductsWithCategories().Skip((page - 1) * 12).Take(12).ToList();
            }
            ListItem lists = new ListItem(products, categories);
            return View(lists);
        }
        public ActionResult Urunler(int id, int page = 1)
        {
            List<ProductCategory> categories = new List<ProductCategory>();
            List<Product> products = new List<Product>();
            ListItem lists = new ListItem(2);
            int productCount = 0;
            using (UnitOfWork uow = new UnitOfWork())
            {
                categories = uow.ProductCategoryRepo.GetAll().ToList();
                productCount = uow.ProductRepo.ProductsWithCategories().ToList().FindAll(x => x.CategoryID == id || x.Category.MainCategoryID == id).Count;
                products = uow.ProductRepo.ProductsWithCategories().ToList().FindAll(x => x.CategoryID == id || x.Category.MainCategoryID == id).Skip((page - 1) * lists.ItemPerPage).Take(lists.ItemPerPage).ToList();
            }
            lists.Products = products;
            lists.Categories = categories;
            lists.CurrentPage = page;
            if (productCount != 0)
            {
                if (productCount % lists.ItemPerPage == 0)
                {
                    lists.PageCount = productCount / lists.ItemPerPage;
                }
                else
                {
                    lists.PageCount = productCount / lists.ItemPerPage + 1;
                }
            }
            else
                lists.PageCount = 1;
            return View(lists);
        }

        public ActionResult UrunDetay(int id)
        {
            using (UnitOfWork uow = new UnitOfWork())
                return View(uow.ProductRepo.GetItemWithCategory(id));
        }
    }
}

OkunmusPirinc.Web/Views/Categories/AltKategoriler.cshtml
@using OkunmusPirinc.Entities.Concretes
@model List<ProductCategory>
@{
    ViewBag.Title = "Alt Kategoriler";
}
<div class="row">
        @Html.Partial("../Partials/_CategoryCard",Model)
</div>

OkunmusPirinc.Web/Views/Categories/AnaKategoriler.cshtml
@using OkunmusPirinc.Entities.Concretes
@model List<ProductCategory>
@{
    ViewBag.Title = "Ana Kategoriler";
}
<div class="row">
        @Html.Partial("../Partials/_CategoryCard",Model)
</div>

OkunmusPirinc.Web/Views/Home/Anasayfa.cshtml
@using OkunmusPirinc.Entities.Concretes
@model ListItem
@{
    ViewBag.Title = "Anasayfa";
}

<div class="row">
    <div class="col-3 mt-3">
        @Html.Partial("../Partials/_SidebarMenu",Model.Categories)
    </div>
    <div class="col-9">
        <div class="row row-cols-3">
                @Html.Partial("../Partials/_ProductList",Model.Products)
        </div>
    </div>
</div>

OkunmusPirinc.Web/Views/Partials/_CategoryCard.cshtml
@using OkunmusPirinc.Entities.Concretes
@model List<ProductCategory>
@foreach (var item in Model)
{
    <div class="col-12 col-sm-6 col-md-4 col-xl-3 mt-3">
        <a href="@Url.Action("AltKategoriler", "Categories", new { id = @item.CategoryID })">
            <div class="category-item position-relative d-flex align-items-center">
                <h3 class="text-white position-absolute w-100 text-center">@item.CategoryName</h3>
                <img src="@item.CategoryImage" alt="@item.CategoryName" />
            </div>
        </a>
    </div>
}

OkunmusPirinc.Web/Views/Partials/_Pagination.cshtml
@using OkunmusPirinc.Entities.Concretes
@model ListItem
<div class="col-12 mt-5" id="pagination" data-active-page="@Model.CurrentPage">
    @if (Model.CurrentPage > 1)
    {
        <a href="@Url.Action("Urunler", "Product", new {page = Model.CurrentPage - 1})" class="pagination-btn"><</a>
    }
    else
    {
        <button class="pagination-btn" disabled><</button>
    }
    @for (
        int i = 1; i <= Model.PageCount; i++)
    {
        <a id="page-@i" href="@Url.Action("Urunler", "Product", new {page = i})" class="pagination-btn">@i</a>
    }

    @if (Model.PageCount > 1 && Model.PageCount != Model.CurrentPage)
    {
        <a href="@Url.Action("Urunler", "Product", new {page = Model.CurrentPage + 1})" class="pagination-btn">></a>
    }
    else
    {
        <button class="pagination-btn" disabled>></button>
    }
</div>

<script>
    let activePage = document.getElementById("pagination").dataset.activePage;
    let activeBtn = document.getElementById("page-" + activePage);
    activeBtn.classList.add("active-page");
</script>

OkunmusPirinc.Web/Views/Partials/_ProductList.cshtml
@using OkunmusPirinc.Entities.Concretes
@model List<Product>
@foreach (var item in Model)
{
    <a href="@Url.Action("UrunDetay", "Product", new { id = item.ProductID })">
        <div class="product-card p-4 mt-3">
            <img class="w-100" src="@item.ProductImage" alt="@item.ProductName" />
            <h4 class="primary-color">@item.ProductName</h4>
            <p class="d-block primary-color-light">
                @if (item.ProductDesc.Length > 106)
                {
                    @(item.ProductDesc.Substring(0, 102) + "...")
                }
                else
                {
                    @item.ProductDesc;
                }
            </p>
            <div class="col-12 mt-1 primary-color">
                <h5 class="d-inline product-price price">@item.ProductPrice</h5>
                @if (item.DiscountPercent > 0)
                {
                    <h5 class="d-inline price discount-price">@(item.ProductPrice - item.ProductPrice * item.DiscountPercent)</h5>
                }
            </div>
        </div>
    </a>
}

OkunmusPirinc.Web/Views/Partials/_SidebarMenu.cshtml
@using OkunmusPirinc.Entities.Concretes
@model List<ProductCategory>
<ul id="sidebarMenu" class="mb-0">
    <li class="main-category bg-dark-color"><a href="#" class="text-white fw-bold">KATEGORİLER</a></li>
    @foreach (var item in Model)
    {
        if (item.MainCategoryID == null)
        {
            <li class="main-category bg-primary-color"><a class="text-white" href="@Url.Action("Urunler", "Product",new {id=item.CategoryID})">@item.CategoryName</a></li>
            <ul>
                @foreach (var subItem in Model)
                {
                    if (subItem.MainCategoryID == item.CategoryID)
                    {
                        <li class="sub-category bg-primary-color-light"><a class="text-white" href="@Url.Action("Urunler", "Product",new {id=subItem.CategoryID})">@subItem.CategoryName</a></li>
                    }
                }
            </ul>
        }
    }
</ul>

OkunmusPirinc.Web/Views/Product/TumUrunler.cshtml
@using OkunmusPirinc.Entities.Concretes
@model ListItem
@{
    ViewBag.Title = "TumUrunler";
}

<div class="row">
    <div class="col-3 mt-3">
        @Html.Partial("../Partials/_SidebarMenu",Model.Categories)
    </div>
    <div class="col-9">
        <div class="row row-cols-3">
                @Html.Partial("../Partials/_ProductList",Model.Products)
        </div>
    </div>
</div>

OkunmusPirinc.Web/Views/Product/UrunDetay.cshtml
@using OkunmusPirinc.Entities.Concretes
@model Product
@{
    ViewBag.Title = Model.ProductName;
}

<div class="row">
    <div class="col-5 p-3" id="zoomContainer" onmousemove="zoomIn(event)" onmouseout="zoomOut()">
        <div id="preview"></div>
        <img id="zoomImage" class="w-100" src="@Model.ProductImage" alt="@Model.ProductName" />
    </div>
    <div class="col-7 p-3">
        <h3 class="text-uppercase">@Model.ProductName</h3>
        <p>@Model.ProductDesc</p>
    </div>
    <hr />
    <div class="col-12">
        <p>
            @Model.ProductExtraDesc
        </p>
    </div>
</div>

<script src="~/Scripts/product-detail.js"></script>

OkunmusPirinc.Web/Views/Product/Urunler.cshtml
@using OkunmusPirinc.Entities.Concretes
@model ListItem
@{
    ViewBag.Title = "Urunler";
}

<div class="row">
    <div class="col-3 mt-3">
        @Html.Partial("../Partials/_SidebarMenu", Model.Categories)
    </div>
    <div class="col-9">
        <div class="row row-cols-3">
            @Html.Partial("../Partials/_ProductList", Model.Products)
        </div>
    </div>
</div>

@Html.Partial("../Partials/_Pagination", Model)

OkunmusPirinc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Okunmuş Store</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
</head>
<body class="light">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="@Url.Action("Anasayfa","Home")">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="@Url.Action("Anasayfa","Home")">Ana Sayfa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("TumUrunler","Product")">Ürünler</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("AnaKategoriler","Categories")">Kategoriler</a>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        @RenderBody()
        <hr class="mt-5" />
        <footer>
            <p>&copy; @DateTime.Now.Year - Okunmuş Store</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>